services:
  db:
    container_name: ship-it-db
    image: bitnami/postgresql
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=event_manager
    restart: unless-stopped
